### ISSUE TITLE
Feature request: Support for additional CSS properties

### ISSUE THREAD

**Issue by lukebennett88** [tokenami/tokenami#228]
I've noticed that the `css` function lacks support for several CSS properties. So far, in my efforts to rebuild a site that was previously using Tailwind, I've encountered `clip`, `fill`, and `stroke` as unsupported. And considering [the vast number of CSS properties available](https://www.w3.org/Style/CSS/all-properties.en.json), there are likely many more.

Is there a method to include these missing properties without modifying Tokenami's source code? Alternatively, if a workaround already exists, I'd be eager to learn about it!

**Comment by jjenzz** [comment]
hi @lukebennett88, thanks for giving tokenami a try ☺️ 

the `fill` and `stroke` properties were overlooked, likely bcos i grabbed all properties i wanted to support [from mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference) and seems they don't list these there 🙈 oops.

`clip` is a [deprecated css property](https://developer.mozilla.org/en-US/docs/Web/CSS/clip) but tokenami does support the recommended `clip-path` that's available in all of [tokenami's supported browsers](https://github.com/tokenami/tokenami?tab=readme-ov-file#supported-browsers).

i have some plans to remove the limitation on supported properties which would solve this, but  in the meantime, feel free to push a PR that adds the properties you are missing [here](https://github.com/tokenami/tokenami/blob/main/packages/config/src/supports.ts) so you aren't blocked. i can merge it ASAP.

the layering is about shorthand vs longhand. there are multiple layers because some longhands are shorthands for other properties. for the specific properties you mentioned, you don't need to worry about this stuff so can list them the first layer.

**Comment by lukebennett88** [comment]
Haha, I was using `clip` for visually hidden styles since that's what everyone seems to use (including [here](https://github.com/radix-ui/primitives/blob/main/packages/react/visually-hidden/src/VisuallyHidden.tsx#L31) 😝).

Just messing around at the moment so not a blocker. Happy to whip up a PR when I get some free time (probably on the weekend).

**Comment by jjenzz** [comment]
heh yeah, radix needs to support a wider set of browsers. tokenami is limited to cascade layer support so i purposefully removed `clip` from supported properties in [this pr](https://github.com/tokenami/tokenami/pull/215).

glad it's not a blocker. i'll hopefully find some time next week to implement #230 🤞
