### ISSUE TITLE
Unsupported CSS properties

### ISSUE THREAD

**Issue by pawelblaszczyk5** [tokenami/tokenami#368]
Currently if I try to use some unsupported property, e.g. "field-sizing" Tokenami 1) gives me a type error and 2) doesn't generate any styles for it. While 1) makes sense obviously, I was hoping that it would generate the styles for it anyway. 

Would it be somehow possible to make it less strict? Or because of the layers ordering Tokenami can't do this?

 I recall this issue and I somehow thought that it works like this already - https://github.com/tokenami/tokenami/issues/228

**Comment by jjenzz** [comment]
@pawelblaszczyk5  this is tricky now because we have the concept of custom properties. for example, if you wanted `--gradient-from` the sheet uses a `supportedProperties` list to determine if it is a custom property or a valid CSS property. valid ones end up like `gradient-from: var(--gradient-from)` while custom ones end up like `--_gradient-from: var(--gradient-from)`. there isn't a way for tokenami to know if `field-sizing` is a valid CSS property or a custom one you're adding.

i agree though, it would be nice to be able to configure this. perhaps something like this:

```tsx
properties: {
  'background-image': ['gradient'],
  'gradient-from': ['color'],
  'gradient-to': ['color'],
  
  // experimental or less widely supported properties can be added here
  experimental: {
    'field-sizing': ['...'], 
  }
}
```

now i can force anything in `experimental` to be considered a supported property. thoughts?

**Comment by jjenzz** [comment]
or maybe i could introduce a breaking change for custom properties so it'd be more like this:

```tsx
properties: {
  'background-image': ['gradient'],
  'field-sizing': ['...'], 
},
customProperties: {
  'gradient-from': ['color'],
  'gradient-to': ['color'],
}
```

**Comment by pawelblaszczyk5** [comment]
Oh, yeah, didn’t think of custom variables 😄 Proposed solution sounds fine to me. Had a few ideas that I thought was “better” but when writing this comment I realized one by one that they wouldn’t work haha

**Comment by jjenzz** [comment]
i am contemplating introducing a breaking change for this and doing this instead:

```tsx
{
  properties: {},
  customProperties: {}
 }
 ```

anything in properties will be considered a css property, and anything in `customProperties` will be a custom css property (css var). this will also allow me to potentially introduce additional config options for custom properties that could help with #332

**Comment by pawelblaszczyk5** [comment]
For me personally this solution would be good 😊
